server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  profiles:
    active: true
  datasource:
    password:
    url: jdbc:h2:mem:cloud
    username: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    cache: true
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true


